name: Build and Deploy PDF Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 25

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==6.0.0

    - name: Create necessary folders
      run: |
        New-Item -ItemType Directory -Force -Path pdf_files, bluetooth_tools

    - name: Download Bluetooth tools
      run: |
        Invoke-WebRequest "https://cdn.example.com/bluetooth_tools/btpair.exe" -OutFile bluetooth_tools/btpair.exe
        Invoke-WebRequest "https://cdn.example.com/bluetooth_tools/btcom.exe" -OutFile bluetooth_tools/btcom.exe

    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --name PDFService `
          --add-data "pdf_files;pdf_files" `
          --add-data "bluetooth_tools;bluetooth_tools" `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFService-Package
        path: |
          dist/PDFService.exe
          pdf_files/
          bluetooth_tools/
