name: Build PDF Service

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==6.0.0

    - name: Create necessary directories
      run: |
        New-Item -ItemType Directory -Force -Path pdf_files

    - name: Build executable
      run: |
        pyinstaller --noconfirm --onefile --windowed --name PDFService `
          --add-data "pdf_files;pdf_files" `
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFService-Package
        path: dist/PDFService.exe
